"""add db

Revision ID: eeeb30a53657
Revises: fb64b859e8ed
Create Date: 2025-12-11 14:10:34.495358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eeeb30a53657'
down_revision: Union[str, Sequence[str], None] = 'fb64b859e8ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
                    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name='users_pkey'),
                    sa.UniqueConstraint('email', name='users_email_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
                    postgresql_ignore_search_path=False
                    )
    op.create_table('chat_requests',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('prompt', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('response', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('chat_requests_user_id_fkey'), ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id', name=op.f('chat_requests_pkey'))
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_requests')
    op.drop_table('users')
    # ### end Alembic commands ###
